### ISSUE TITLE
Unable to compile nadist

### ISSUE THREAD

**Issue by gsever** [Midnighter/nadist#1]
Hello,

Not sure it is the best way to report these issues, but I can't seem to get Cython/C packages compiling on Windows and Linux:

Windows:
building 'nadist.ccode.src.spatial_wrap' extension

---

WARNING:

```
An optional code optimization (C extension) could not be compiled.

Optimizations for this package will not be available!
```

CAUSE:

```
UnknownFileError("unknown file type '.pyx' (from 'src\\nadist\\ccode\\src\\spatial_wrap.pyx')",)
```

Linux:
gcc -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc/nadist/cython -I/home/gs/anaconda3/include/python3.5m -c src/nadist/cython/spatial.c -o build/temp.linux-x86_64-3.5/src/nadist/cython/spatial.o
src/nadist/cython/spatial.c:267:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.

---

WARNING:

```
An optional code optimization (C extension) could not be compiled.

Optimizations for this package will not be available!
```

CAUSE:

```
CompileError(DistutilsExecError("command 'gcc' failed with exit status 1",),)
```

Any ideas to get these resolved? Thanks.

**Comment by gsever** [comment]
Update, fixed Linux error, by adding include_dirs=[numpy.get_include()] by following the suggestion from:
http://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory

**Comment by Midnighter** [comment]
> Not sure it is the best way to report these issues, but I can't seem to get Cython/C packages compiling on Windows and Linux

This is absolutely the right place. Thank you for being persistent. I've had the same problems compiling on Travis CI, too, so I'm glad you've identified a potential source. It's strange that I was able to compile it (I'm on Linux, too, and just tried with a fresh, empty virtualenv).

**Comment by Midnighter** [comment]
I don't have a windows platform available myself but it will need some C compiler. After sorting out Travis I'll make it work on AppVeyor.

**Comment by gsever** [comment]
Thanks. These issues get resolved easily on Linux, yet involves a lot of steps in Windows. In this particular case, it requires a compiler re-installation. I usually use binaries from Gohlke's page on Windows. Let me know if you get a binary for Win64, Python 3. Also I will have two more questions, could I send them as e-mail?

**Comment by Midnighter** [comment]
Absolutely, midnighter[you know what]posteo.net
